'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { AlertTriangle, CheckCircle2, Clock3, FileCheck2, Inbox, Loader2, MessageCircleQuestion, RefreshCw, Search, UserCheck, Zap } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type CaseStatus = 'new'|'needs_info'|'standard'|'human_review'|'in_progress'|'waiting'|'done'
type Urgency = 'low'|'normal'|'high'|'critical'
type CaseItem = { id:string; source:string; caller_name:string|null; company:string|null; phone:string|null; email:string|null; subject:string; summary:string; urgency:Urgency; category:string; status:CaseStatus; assigned_to:string|null; due_at:string|null; handoff_summary:string|null; handoff_ready:boolean; created_at:string; completed_at:string|null }
type Task = { id:string; case_id:string|null; title:string; status:'open'|'waiting'|'blocked'|'done'; due_at:string|null; next_action:string|null }
type Update = { id:string; case_id:string; kind:'question'|'answer'|'note'|'handoff'; content:string; status:'open'|'waiting'|'done'; created_at:string }
type Filter = 'all'|'today'|'waiting'|'review'|'ready'|'done'

const STATUS_LABEL:Record<CaseStatus,string>={new:'Neu',needs_info:'Info fehlt',standard:'Standard',human_review:'Mensch prüfen',in_progress:'In Bearbeitung',waiting:'Wartet',done:'Erledigt'}
function dueLevel(value:string|null){if(!value)return'normal';const diff=new Date(value).getTime()-Date.now();if(diff<0)return'overdue';if(diff<86400000)return'today';return'normal'}
function formatDate(value:string|null){if(!value)return'Keine Frist';return new Date(value).toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function personLabel(item:CaseItem){return item.caller_name||item.company||'Kontakt noch offen'}

export default function JetztPage(){
 const [cases,setCases]=useState<CaseItem[]>([]),[tasks,setTasks]=useState<Task[]>([]),[updates,setUpdates]=useState<Update[]>([])
 const [selectedId,setSelectedId]=useState<string|null>(null),[filter,setFilter]=useState<Filter>('all'),[query,setQuery]=useState('')
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{void load()},[])
 async function load(){setLoading(true);setError('');const{data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Bitte zuerst anmelden.');setLoading(false);return}const[c,t,u]=await Promise.all([supabase.from('mila_intake_cases').select('*').order('created_at',{ascending:false}).limit(200),supabase.from('mila_coordination_tasks').select('*').order('created_at',{ascending:false}).limit(400),supabase.from('mila_case_updates').select('*').order('created_at',{ascending:true}).limit(800)]);if(c.error||t.error||u.error)setError('Mila konnte die Vorgänge nicht vollständig laden.');setCases((c.data||[])as CaseItem[]);setTasks((t.data||[])as Task[]);setUpdates((u.data||[])as Update[]);setSelectedId(x=>x||((c.data||[])[0]?.id??null));setLoading(false)}
 const current=cases.find(x=>x.id===selectedId)||null,currentTasks=tasks.filter(x=>x.case_id===selectedId),currentUpdates=updates.filter(x=>x.case_id===selectedId)
 const openQuestions=(id:string)=>updates.filter(u=>u.case_id===id&&u.kind==='question'&&u.status!=='done').length
 const openTasks=(id:string)=>tasks.filter(t=>t.case_id===id&&t.status!=='done').length
 const isTodayFirst=(item:CaseItem)=>item.status!=='done'&&(item.urgency==='critical'||item.urgency==='high'||dueLevel(item.due_at)==='today'||dueLevel(item.due_at)==='overdue'||openQuestions(item.id)>0)
 const stats=useMemo(()=>({open:cases.filter(c=>c.status!=='done').length,today:cases.filter(isTodayFirst).length,waiting:cases.filter(c=>c.status==='waiting'||openQuestions(c.id)>0).length,ready:cases.filter(c=>c.handoff_ready&&c.status!=='done').length}),[cases,updates])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return cases.filter(item=>{const text=`${item.subject} ${item.summary} ${item.caller_name||''} ${item.company||''} ${item.category}`.toLowerCase();if(q&&!text.includes(q))return false;if(filter==='today')return isTodayFirst(item);if(filter==='waiting')return item.status==='waiting'||openQuestions(item.id)>0;if(filter==='review')return item.status==='human_review';if(filter==='ready')return item.handoff_ready&&item.status!=='done';if(filter==='done')return item.status==='done';return item.status!=='done'})},[cases,tasks,updates,query,filter])
 async function setStatus(status:CaseStatus){if(!current)return;setSaving(true);const{error:e}=await supabase.from('mila_intake_cases').update({status}).eq('id',current.id);if(e)setError('Status konnte nicht aktualisiert werden.');else setNotice(`Vorgang ist jetzt „${STATUS_LABEL[status]}“.`);setSaving(false);await load()}
 async function closeTask(task:Task){setSaving(true);await supabase.from('mila_coordination_tasks').update({status:'done'}).eq('id',task.id);setSaving(false);await load()}
 async function closeQuestion(update:Update){setSaving(true);await supabase.from('mila_case_updates').update({status:'done'}).eq('id',update.id);setSaving(false);await load()}
 async function prepareHandoff(){if(!current)return;const questions=currentUpdates.filter(u=>u.kind==='question'&&u.status!=='done');if(questions.length){setError('Übergabe noch nicht möglich: Es sind Rückfragen offen.');return}const summary=[`Anliegen: ${current.subject}`,`Kontakt: ${personLabel(current)}`,current.phone?`Telefon: ${current.phone}`:null,current.email?`E-Mail: ${current.email}`:null,`Zusammenfassung: ${current.summary}`,`Zuständig: ${current.assigned_to||'noch offen'}`].filter(Boolean).join('\n');setSaving(true);const{error:e}=await supabase.from('mila_intake_cases').update({handoff_summary:summary,handoff_ready:true,status:'human_review'}).eq('id',current.id);if(e)setError('Übergabe konnte nicht vorbereitet werden.');else setNotice('Übergabe ist vorbereitet und wartet auf menschliche Prüfung.');setSaving(false);await load()}
 async function finishCase(){if(!current)return;const t=currentTasks.filter(x=>x.status!=='done'),q=currentUpdates.filter(x=>x.kind==='question'&&x.status!=='done');if(!current.handoff_ready||t.length||q.length){setError('Noch nicht abschließen: Übergabe, Aufgaben oder Rückfragen sind noch offen.');return}setSaving(true);const{error:e}=await supabase.from('mila_intake_cases').update({status:'done',completed_at:new Date().toISOString()}).eq('id',current.id);if(e)setError('Vorgang konnte nicht abgeschlossen werden.');else setNotice('Vorgang vollständig abgeschlossen.');setSaving(false);await load()}
 return <main className="min-h-screen bg-[#faf9fc] pb-28 lg:pb-8"><div className="mx-auto w-full max-w-[1220px] px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-violet-100 px-3 py-1 text-[10px] font-black uppercase tracking-[.16em] text-violet-700"><Zap className="h-3.5 w-3.5"/>Vorgänge</div><h1 className="mt-3 text-3xl font-black tracking-tight lg:text-4xl">Was muss wirklich weiter?</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-slate-500">Mila hält jeden Eingang offen, bis Rückfragen, Aufgaben und Übergabe geklärt sind. Kein Vorgang verschwindet zwischen Anruf, Mail und Kanzlei.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-black"><RefreshCw className="h-4 w-4"/>Aktualisieren</button><Link href="/eingang" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-xs font-black text-white"><Inbox className="h-4 w-4"/>Neuer Eingang</Link></div></header>
  <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi label="Offen" value={stats.open} icon={<Zap className="h-4 w-4"/>} tone="violet"/><Kpi label="Heute zuerst" value={stats.today} icon={<AlertTriangle className="h-4 w-4"/>} tone="rose"/><Kpi label="Wartet" value={stats.waiting} icon={<Clock3 className="h-4 w-4"/>} tone="amber"/><Kpi label="Übergabebereit" value={stats.ready} icon={<FileCheck2 className="h-4 w-4"/>} tone="green"/></section>
  {notice&&<p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{notice}</p>}{error&&<p className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</p>}
  <section className="mt-6 grid gap-4 lg:grid-cols-[minmax(0,.95fr)_minmax(0,1.35fr)]"><div className="rounded-2xl border bg-white p-3 shadow-sm lg:p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Vorgänge durchsuchen…" className="w-full rounded-xl border bg-slate-50 py-2.5 pl-9 pr-3 text-sm font-semibold outline-none"/></div><div className="mt-3 flex flex-wrap gap-2">{([['all','Offen'],['today','Heute zuerst'],['waiting','Wartet'],['review','Mensch prüfen'],['ready','Übergabebereit'],['done','Erledigt']]as[Filter,string][]).map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={filter===v?'rounded-lg bg-violet-600 px-3 py-1.5 text-[10px] font-black text-white':'rounded-lg bg-slate-100 px-3 py-1.5 text-[10px] font-black text-slate-600'}>{l}</button>)}</div><div className="mt-4 space-y-2">{loading?<div className="flex items-center justify-center gap-2 py-12 text-sm font-bold text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Vorgänge werden geladen…</div>:visible.length===0?<div className="rounded-xl border border-dashed p-6 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-emerald-500"/><p className="mt-2 text-sm font-black">Hier ist gerade nichts offen.</p></div>:visible.map(item=><CaseRow key={item.id} item={item} selected={item.id===selectedId} questions={openQuestions(item.id)} tasks={openTasks(item.id)} onClick={()=>setSelectedId(item.id)}/>)}</div></div>
   <div className="min-w-0">{!current?<div className="rounded-2xl border border-dashed bg-white p-10 text-center shadow-sm"><Zap className="mx-auto h-8 w-8 text-violet-500"/><p className="mt-3 font-black">Wähle links einen Vorgang.</p></div>:<div className="space-y-4"><section className="rounded-2xl border bg-white p-4 shadow-sm lg:p-5"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.16em] text-violet-500">Aktiver Vorgang</p><h2 className="mt-1 text-2xl font-black">{current.subject}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{current.summary}</p></div><StatusBadge status={current.status}/></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4"><Info label="Kontakt" value={personLabel(current)}/><Info label="Zuständig" value={current.assigned_to||'Noch offen'}/><Info label="Frist" value={formatDate(current.due_at)}/><Info label="Priorität" value={current.urgency}/></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void setStatus('in_progress')} disabled={saving} className="rounded-xl bg-violet-600 px-3 py-2 text-xs font-black text-white">In Bearbeitung</button><button onClick={()=>void setStatus('waiting')} disabled={saving} className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-black text-amber-700">Wartet auf Antwort</button><button onClick={()=>void setStatus('human_review')} disabled={saving} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-black">Mensch prüfen</button></div></section>
   <section className="grid gap-4 md:grid-cols-2"><WorkCard title="Aufgaben / Übernahme" icon={<UserCheck className="h-4 w-4"/>}>{currentTasks.length===0?<EmptyLine text="Keine Aufgaben angelegt."/>:currentTasks.map(task=><div key={task.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-black">{task.title}</p>{task.next_action&&<p className="mt-1 text-xs leading-5 text-slate-500">{task.next_action}</p>}<p className="mt-1 text-[10px] font-bold text-slate-400">{formatDate(task.due_at)}</p></div>{task.status!=='done'?<button onClick={()=>void closeTask(task)} className="h-fit rounded-lg bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">Erledigt</button>:<CheckCircle2 className="h-4 w-4 text-emerald-500"/>}</div></div>)}</WorkCard><WorkCard title="Rückfragen & Verlauf" icon={<MessageCircleQuestion className="h-4 w-4"/>}>{currentUpdates.length===0?<EmptyLine text="Noch keine Rückfragen oder Notizen."/>:currentUpdates.map(update=><div key={update.id} className="rounded-xl border p-3"><p className="text-[9px] font-black uppercase tracking-[.12em] text-violet-500">{update.kind}</p><p className="mt-1 text-xs font-semibold leading-5 text-slate-700">{update.content}</p>{update.kind==='question'&&update.status!=='done'&&<button onClick={()=>void closeQuestion(update)} className="mt-2 text-[10px] font-black text-emerald-700">Als geklärt markieren</button>}</div>)}</WorkCard></section>
   <section className="rounded-2xl border border-violet-100 bg-white p-4 shadow-sm lg:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-violet-500">Übergabe</p><h3 className="mt-1 text-lg font-black">{current.handoff_ready?'Bereit für die fachliche Prüfung':'Noch nicht übergabebereit'}</h3></div>{current.handoff_ready?<FileCheck2 className="h-6 w-6 text-emerald-500"/>:<Clock3 className="h-6 w-6 text-amber-500"/>}</div>{current.handoff_summary&&<pre className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-xs font-semibold leading-5 text-slate-600">{current.handoff_summary}</pre>}<div className="mt-4 flex flex-col gap-2 sm:flex-row">{!current.handoff_ready&&<button onClick={()=>void prepareHandoff()} disabled={saving} className="flex-1 rounded-xl bg-violet-600 px-4 py-3 text-xs font-black text-white">Übergabe vorbereiten</button>}<button onClick={()=>void finishCase()} disabled={saving||current.status==='done'} className="flex-1 rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white disabled:opacity-40">Vorgang vollständig abschließen</button></div></section></div>}</div></section>
 </div></main>
}
function Kpi({label,value,icon,tone}:{label:string;value:number;icon:React.ReactNode;tone:'violet'|'rose'|'amber'|'green'}){const c={violet:'bg-violet-50 text-violet-700',rose:'bg-rose-50 text-rose-600',amber:'bg-amber-50 text-amber-700',green:'bg-emerald-50 text-emerald-700'};return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className={`inline-flex h-8 w-8 items-center justify-center rounded-xl ${c[tone]}`}>{icon}</div><p className="mt-3 text-2xl font-black">{value}</p><p className="text-xs font-bold text-slate-500">{label}</p></div>}
function CaseRow({item,selected,questions,tasks,onClick}:{item:CaseItem;selected:boolean;questions:number;tasks:number;onClick:()=>void}){const level=dueLevel(item.due_at);return <button onClick={onClick} className={selected?'w-full rounded-xl border border-violet-300 bg-violet-50 p-3 text-left':'w-full rounded-xl border bg-white p-3 text-left hover:bg-slate-50'}><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black">{item.subject}</p><p className="mt-.5 truncate text-[11px] font-semibold text-slate-500">{personLabel(item)} · {item.category}</p></div>{item.handoff_ready&&<FileCheck2 className="h-4 w-4 text-emerald-500"/>}</div><div className="mt-2 flex flex-wrap gap-1.5"><span className={`rounded-md px-2 py-1 text-[9px] font-black ${level==='overdue'?'bg-rose-50 text-rose-600':level==='today'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-500'}`}>{formatDate(item.due_at)}</span>{questions>0&&<span className="rounded-md bg-amber-50 px-2 py-1 text-[9px] font-black text-amber-700">{questions} Rückfrage{questions===1?'':'n'}</span>}{tasks>0&&<span className="rounded-md bg-violet-50 px-2 py-1 text-[9px] font-black text-violet-700">{tasks} Aufgabe{tasks===1?'':'n'}</span>}</div></button>}
function StatusBadge({status}:{status:CaseStatus}){return <span className="h-fit shrink-0 rounded-lg bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">{STATUS_LABEL[status]}</span>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 truncate text-xs font-black">{value}</p></div>}
function WorkCard({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-violet-700">{icon}<h3 className="text-sm font-black text-slate-950">{title}</h3></div><div className="mt-3 space-y-2">{children}</div></section>}
function EmptyLine({text}:{text:string}){return <p className="rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-500">{text}</p>}
