'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Clock3, FileText, FolderOpen, MessageCircle, Search, Upload } from 'lucide-react'
import { useFinance } from '@/lib/store'
import { getActiveClientId, supabase } from '@/lib/supabase'
import { buildDocumentWorkName, checkDocumentQuality } from '@/lib/document-workflow'

type CaseItem={id:string;client_id:string|null;subject:string;summary:string;status:string;handoff_ready:boolean;created_at:string}
type Task={id:string;case_id:string|null;title:string;status:string;next_action:string|null}
type Update={id:string;case_id:string;kind:'question'|'answer'|'note'|'handoff';content:string;status:'open'|'waiting'|'done'}
type View='all'|'issues'|'ready'

function itemDate(i:any){return String(i?.date||i?.documentDate||i?.document_date||i?.createdAt||i?.created_at||'')}
function monthKey(i:any){const raw=itemDate(i),d=raw?new Date(raw):new Date();return Number.isNaN(d.getTime())?'Ohne Datum':new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(d)}

export default function DokumentePage(){
 const{documents}=useFinance();const[clientId,setClientId]=useState(''),[clientName,setClientName]=useState(''),[cases,setCases]=useState<CaseItem[]>([]),[tasks,setTasks]=useState<Task[]>([]),[updates,setUpdates]=useState<Update[]>([]),[caseId,setCaseId]=useState(''),[view,setView]=useState<View>('all'),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{const id=getActiveClientId();setClientId(id);void load(id)},[])
 async function load(id=clientId){setError('');if(!id)return;const{data:a}=await supabase.auth.getUser();if(!a.user)return;const[c,cs,t,u]=await Promise.all([supabase.from('clients').select('id,name').eq('id',id).maybeSingle(),supabase.from('mila_intake_cases').select('id,client_id,subject,summary,status,handoff_ready,created_at').eq('client_id',id).order('created_at',{ascending:false}),supabase.from('mila_coordination_tasks').select('id,case_id,title,status,next_action').order('created_at',{ascending:false}),supabase.from('mila_case_updates').select('id,case_id,kind,content,status').order('created_at',{ascending:true})]);if(c.data?.name)setClientName(String(c.data.name));if(cs.error||t.error||u.error)setError('Mila konnte die Arbeitsakte nicht vollständig laden.');const next=(cs.data||[]) as CaseItem[];setCases(next);setTasks((t.data||[]) as Task[]);setUpdates((u.data||[]) as Update[]);setCaseId(x=>x&&next.some(i=>i.id===x)?x:(next.find(i=>i.status!=='done')?.id||next[0]?.id||''))}
 const current=cases.find(i=>i.id===caseId)||null,openTasks=tasks.filter(i=>i.case_id===caseId&&i.status!=='done'),openQuestions=updates.filter(i=>i.case_id===caseId&&i.kind==='question'&&i.status!=='done')
 const issues=useMemo(()=>documents.filter((d:any)=>!checkDocumentQuality(d).ok),[documents]),issueIds=useMemo(()=>new Set(issues.map((d:any)=>String(d.id))),[issues])
 const filtered=useMemo(()=>{const n=query.trim().toLowerCase();return[...documents].filter((d:any)=>{const bad=issueIds.has(String(d.id)),text=`${d.title||''} ${d.partner||''} ${d.note||''} ${d.type||''} ${d.file_name||''}`.toLowerCase();if(n&&!text.includes(n))return false;if(view==='issues')return bad;if(view==='ready')return!bad;return true}).sort((a:any,b:any)=>new Date(itemDate(b)||0).getTime()-new Date(itemDate(a)||0).getTime())},[documents,query,view,issueIds])
 const groups=useMemo(()=>{const m=new Map<string,any[]>();for(const d of filtered){const k=monthKey(d);m.set(k,[...(m.get(k)||[]),d])}return Array.from(m.entries())},[filtered])
 const canHandoff=Boolean(current)&&documents.length>0&&issues.length===0&&openTasks.length===0&&openQuestions.length===0
 async function handoff(){if(!current||!canHandoff){setError('Noch nicht übergabebereit. Mila zeigt, was im Vorgang noch offen ist.');return}setSaving(true);setError('');const summary=`Akte: ${clientName}\nVorgang: ${current.subject}\nDokumente: ${documents.length}\nOrganisatorisch vollständig: ja`;const{error:e}=await supabase.from('mila_intake_cases').update({handoff_ready:true,handoff_summary:summary,status:'human_review'}).eq('id',current.id);if(e){setError(e.message);setSaving(false);return}const{data:a}=await supabase.auth.getUser();if(a.user)await supabase.from('mila_case_updates').insert({user_id:a.user.id,case_id:current.id,kind:'handoff',content:summary,status:'open'});setNotice('Übergabe vorbereitet. Dieser Vorgang ist jetzt für die fachliche Prüfung bereit.');setSaving(false);await load()}
 if(!clientId)return <main className="min-h-screen bg-[#faf9fc] p-5 pb-28"><div className="mx-auto max-w-2xl rounded-3xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-violet-600">Arbeitsakte</p><h1 className="mt-2 text-3xl font-black">Bitte zuerst oben eine Akte wählen.</h1><p className="mt-3 text-sm font-semibold text-slate-500">Danach zeigt Mila nur noch die Vorgänge und Unterlagen dieses Mandanten.</p></div></main>
 return <main className="min-h-screen bg-[#faf9fc] px-4 pb-28 pt-5 text-slate-950 sm:px-6 lg:px-8 lg:pb-10 lg:pt-8"><div className="mx-auto max-w-[1220px]">
  <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.18em] text-violet-600">Arbeitsakte</p><h1 className="mt-1 text-3xl font-black lg:text-4xl">{clientName||'Aktive Akte'}</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-slate-500">Ein Mandant, seine Vorgänge, Rückfragen und Unterlagen. Mila hält alles bis zur Übergabe zusammen.</p></div><Link href="/neue-buchungen" className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-sm font-black text-white"><Upload className="h-4 w-4"/> Unterlagen hinzufügen</Link></header>
  {notice&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{notice}</p>}{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</p>}
  <div className="mt-6 grid gap-5 lg:grid-cols-[320px_minmax(0,1fr)]"><aside className="space-y-4"><section className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Aktiver Vorgang</p><select value={caseId} onChange={e=>setCaseId(e.target.value)} className="mt-3 w-full rounded-xl border p-3 text-sm font-bold"><option value="">Vorgang auswählen</option>{cases.map(i=><option key={i.id} value={i.id}>{i.subject}</option>)}</select>{current&&<div className="mt-3 rounded-xl bg-violet-50 p-3"><p className="text-xs font-black text-violet-900">{current.subject}</p><p className="mt-1 text-[11px] font-semibold leading-5 text-violet-700">{current.summary||'Keine Zusammenfassung hinterlegt.'}</p><Link href={`/jetzt?case=${current.id}`} className="mt-3 inline-flex text-xs font-black text-violet-700">Vorgang öffnen →</Link></div>}</section>
  <section className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Noch offen</p><div className="mt-3 space-y-3"><State ok={openQuestions.length===0} icon={<MessageCircle className="h-4 w-4"/>} text={openQuestions.length?`${openQuestions.length} Rückfrage(n) offen`:'Keine Rückfrage offen'}/><State ok={openTasks.length===0} icon={<Clock3 className="h-4 w-4"/>} text={openTasks.length?`${openTasks.length} Arbeitsschritt(e) offen`:'Kein Arbeitsschritt offen'}/><State ok={issues.length===0&&documents.length>0} icon={<FileText className="h-4 w-4"/>} text={documents.length===0?'Noch keine Unterlagen':issues.length?`${issues.length} Dokument(e) brauchen Klärung`:'Unterlagen organisatorisch vollständig'}/></div><button onClick={()=>void handoff()} disabled={!canHandoff||saving} className={`mt-4 w-full rounded-xl py-3 text-sm font-black ${canHandoff?'bg-emerald-600 text-white':'bg-slate-100 text-slate-400'}`}>{saving?'Mila bereitet vor…':'Für fachliche Prüfung vorbereiten'}</button></section></aside>
  <section className="space-y-4"><section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex gap-2"><Tab active={view==='all'} onClick={()=>setView('all')} label={`Alle ${documents.length}`}/><Tab active={view==='issues'} onClick={()=>setView('issues')} label={`Klärung ${issues.length}`}/><Tab active={view==='ready'} onClick={()=>setView('ready')} label={`Bereit ${Math.max(0,documents.length-issues.length)}`}/></div><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Unterlagen durchsuchen…" className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm outline-none"/></label></div></section>
  {openQuestions[0]&&current&&<section className="rounded-2xl border border-amber-100 bg-amber-50 p-4"><p className="text-[10px] font-black uppercase text-amber-600">Mila braucht noch Kontext</p><div className="mt-1 flex items-start justify-between gap-3"><h2 className="text-lg font-black">{openQuestions[0].content}</h2><Link href={`/jetzt?case=${current.id}`} className="shrink-0 text-xs font-black text-violet-700">Antworten →</Link></div></section>}
  {openTasks[0]&&<section className="rounded-2xl border border-violet-100 bg-white p-4"><p className="text-[10px] font-black uppercase text-violet-600">Nächster Schritt</p><h2 className="mt-1 text-lg font-black">{openTasks[0].next_action||openTasks[0].title}</h2></section>}
  <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-violet-600">Unterlagen der aktiven Akte</p><h2 className="mt-1 text-lg font-black">{filtered.length} Dokument{filtered.length===1?'':'e'}</h2></div><FolderOpen className="h-5 w-5 text-violet-500"/></div>{groups.length===0?<p className="mt-5 rounded-xl border border-dashed p-6 text-center text-sm font-semibold text-slate-500">Keine Unterlagen in dieser Ansicht.</p>:<div className="mt-4 space-y-5">{groups.map(([month,docs])=><div key={month}><div className="mb-2 flex justify-between"><h3 className="text-sm font-black">{month}</h3><span className="text-[10px] font-bold text-slate-400">{docs.length} Dokumente</span></div><div className="space-y-2">{docs.map((d:any)=>{const bad=issueIds.has(String(d.id));return <div key={d.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><p className="truncate text-sm font-black">{buildDocumentWorkName(d,d.type||'Dokument')}</p><p className="truncate text-[11px] font-semibold text-slate-400">{d.partner||d.type||'Unterlage'}</p></div><span className={`rounded-lg px-2 py-1 text-[10px] font-black ${bad?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{bad?'Klärung':'Erfasst'}</span></div>})}</div></div>)}</div>}</section></section></div>
 </div></main>
}
function Tab({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`rounded-xl px-3 py-2 text-xs font-black ${active?'bg-violet-600 text-white':'bg-slate-50 text-slate-600'}`}>{label}</button>}
function State({ok,icon,text}:{ok:boolean;icon:React.ReactNode;text:string}){return <div className="flex items-center gap-2 text-xs font-semibold text-slate-600"><span className={ok?'text-emerald-600':'text-amber-600'}>{ok?<CheckCircle2 className="h-4 w-4"/>:icon}</span>{text}</div>}
