'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

type Question={id:string;question:string;answer?:string;status:string}
export default function MandantUploadPage(){
 const [token,setToken]=useState(''); const [clientId,setClientId]=useState(''); const [questions,setQuestions]=useState<Question[]>([]); const [answers,setAnswers]=useState<Record<string,string>>({}); const [message,setMessage]=useState(''); const [ready,setReady]=useState(false)
 useEffect(()=>{ const t=new URLSearchParams(location.search).get('token')||''; setToken(t); void init(t)},[])
 async function init(t:string){ if(!t){setMessage('Dieser Upload-Link ist unvollständig.');setReady(true);return}; const {data:link}=await supabase.from('client_upload_links').select('client_id,active').eq('token',t).eq('active',true).maybeSingle(); if(!link){setMessage('Dieser Upload-Link ist nicht mehr gültig.');setReady(true);return}; setClientId(link.client_id); const {data}=await supabase.from('client_questions').select('id,question,answer,status').eq('client_id',link.client_id).neq('status','erledigt').order('created_at',{ascending:false}); setQuestions((data||[]) as Question[]); setReady(true) }
 async function answer(q:Question){ const text=(answers[q.id]||'').trim(); if(!text)return; const {error}=await supabase.from('client_questions').update({answer:text,status:'beantwortet',answered_at:new Date().toISOString()}).eq('id',q.id).eq('client_id',clientId); if(error){setMessage(error.message);return}; setMessage('Antwort wurde übermittelt. Danke.'); await init(token) }
 return <main className="mx-auto min-h-screen max-w-md space-y-5 p-5 pb-20 text-slate-950"><header className="rounded-[2rem] bg-gradient-to-br from-violet-700 to-fuchsia-500 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-white/70">Mila · sicherer Mandantenbereich</p><h1 className="mt-2 text-3xl font-black">Unterlagen & Rückfragen</h1><p className="mt-3 text-sm font-semibold text-white/85">Hier können offene Angaben beantwortet und Nachreichungen vorbereitet werden.</p></header>{message&&<div className="rounded-2xl bg-violet-50 p-4 text-sm font-bold text-violet-800">{message}</div>}{ready&&questions.length===0&&clientId&&<div className="rounded-3xl bg-emerald-50 p-5 font-semibold text-emerald-800">✓ Aktuell sind keine Rückfragen offen.</div>}{questions.map(q=><section key={q.id} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[.16em] text-violet-600">Rückfrage</p><h2 className="mt-2 text-lg font-black">{q.question}</h2>{q.answer?<p className="mt-3 rounded-2xl bg-emerald-50 p-3 text-sm font-semibold">Antwort gesendet: {q.answer}</p>:<><textarea value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} rows={3} placeholder="Antwort eingeben …" className="mt-4 w-full resize-none rounded-2xl border border-slate-200 p-4 font-semibold"/><button onClick={()=>void answer(q)} className="mt-3 w-full rounded-2xl bg-violet-600 p-4 font-black text-white">Antwort senden</button></>}</section>)}<section className="rounded-3xl border border-dashed border-violet-200 bg-violet-50 p-5"><p className="font-black text-violet-800">Beleg nachreichen</p><p className="mt-2 text-sm font-semibold text-slate-600">Der direkte Datei-Upload wird im nächsten technischen Schritt an Mila Storage angeschlossen. Antworten auf Rückfragen funktionieren über diesen Bereich bereits.</p></section></main>
}
